name = "CloudRegistry"
uuid = "e0a6cdac-8035-45e4-94bc-3e3ed992f74d"
repo = "git@github.com:cloudmrhub-com/CloudRegistry.git"
description = "CloudMR Julia Registry"

[packages]
6ba24435-1b4f-4a37-bd7b-5547d061c7b4 = { name = "KomaNYU", path = "K/KomaNYU" }
