name = "CloudRegistry"
uuid = "e0a6cdac-8035-45e4-94bc-3e3ed992f74d"
repo = "git@github.com:cloudmrhub-com/CloudRegistry.git"
description = "CloudMR Julia Registry"

[packages]
558670ff-cef0-4d9f-b15b-bd345d36ea0a = { name = "KomaNYUBase", path = "K/KomaNYUBase" }
6ba24435-1b4f-4a37-bd7b-5547d061c7b4 = { name = "KomaNYU", path = "K/KomaNYU" }
8ddc4e30-e12a-441d-8de6-881fa077b415 = { name = "KomaNYUFiles", path = "K/KomaNYUFiles" }
a4d5918d-f7c8-4203-8706-5b9a82e83504 = { name = "KomaNYUCore", path = "K/KomaNYUCore" }
